export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const EDUCATION_LEVELS = [
  '10th Pass',
  '12th Pass',
  'Graduate',
  'Post Graduate',
  'Diploma',
  'Professional Degree',
  'Other',
];

export const COORDINATOR_ROLES = [
  { value: 'applicant', label: 'Swastha Sangini Applicant' },
  { value: 'district_coordinator', label: 'District Coordinator' },
  { value: 'block_coordinator', label: 'Block Coordinator' },
  { value: 'panchayat_coordinator', label: 'Panchayat Coordinator' },
];
